import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OS System - professional",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className= 'dark' >
      <body className=" h-screen p-3 text-zinc-950 bg-zinc-100 dark:bg-zinc-950 dark:text-zinc-200">{children}</body>
    </html>
  );
}
